[build]
  command = "ng build --configuration production"
  publish = "dist/weather/browser"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/angular-runtime"
  enabled = false